const products = [
  {
    name: 'Smartphone',
    slug: 'smartphone',
    description: 'A high-end smartphone',
    price: 999.99,
    quantity: 50,
    shipping: false,
    category: 'Electronics',
    imageUrl: 'https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/pTwAAOSw4ytjAe-K/$_57.JPG',
  },
  {
    name: 'Laptop',
    slug: 'laptop',
    description: 'A powerful laptop',
    price: 1499.99,
    quantity: 30,
    shipping: true,
    category: 'Electronics',
    imageUrl: 'https://hips.hearstapps.com/popularmechanics/assets/16/17/1461938344-lte.jpg',
  },
  {
    name: 'T-shirt',
    slug: 't-shirt',
    description: 'A comfortable cotton t-shirt',
    price: 19.99,
    quantity: 100,
    shipping: true,
    category: 'Clothing',
    imageUrl: 'https://m.media-amazon.com/images/I/41kakP2KLaL._AC_.jpg',
  },
  {
    name: 'Jeans',
    slug: 'jeans',
    description: 'Classic denim jeans',
    price: 49.99,
    quantity: 75,
    shipping: true,
    category: 'Clothing',
    imageUrl: 'https://i.kym-cdn.com/photos/images/newsfeed/000/859/869/c35.jpg',
  },
  {
    name: 'Novel',
    slug: 'novel',
    description: 'A bestselling novel',
    price: 14.99,
    quantity: 200,
    shipping: true,
    category: 'Books',
    imageUrl: 'https://m.media-amazon.com/images/I/81xrAw9CfkL._AC_UF1000,1000_QL80_.jpg',
  },
  {
    name: 'Textbook',
    slug: 'textbook',
    description: 'A comprehensive textbook',
    price: 79.99,
    quantity: 50,
    shipping: false,
    category: 'Books',
    imageUrl: 'https://m.media-amazon.com/images/I/616vW1CCBOL._SY466_.jpg',
  },
];

export default products;